from typing import Annotated, Any, Literal, Optional

from pydantic import BaseModel, Field

from app.mcp_app import mcp
from supabase_edge_client import call_sup_fun


class CreateActionModel(BaseModel):
	id: str = Field(
		description="Action ID, typically a UUID generated by the planner.",
		min_length=1,
	)
	capabilityId: str = Field(
		description="Capability ID that specifies which capability this action should execute.",
		min_length=1,
	)
	parameters: dict[str, Any] = Field(
		default_factory=dict,
		description="Capability input parameters for this action.",
	)
	assignsArtifactIds: Optional[list[str]] = Field(
		default=None,
		description="Optional artifact IDs produced by this action, positionally matching produced artifacts.",
	)
	expectsArtifacts: Optional[list[str]] = Field(
		default=None,
		description="Optional artifact IDs that this action expects as inputs.",
	)
	requiresUserApproval: Optional[bool] = Field(
		default=None,
		description="Whether this action should wait for explicit user approval before execution.",
	)


class CreateOperationModel(BaseModel):
	name: str = Field(
		description="Human-readable operation name.",
		min_length=1,
	)
	actions: list[CreateActionModel] = Field(
		description="Ordered list of actions that belong to this operation.",
		min_length=1,
	)


class CreateScheduleModel(BaseModel):
	type: Literal["ONE_TIME", "RECURRING"] = Field(
		description="Schedule type. Use ONE_TIME for one run or RECURRING for repeated runs.",
	)
	config: dict[str, Any] = Field(
		description=(
			"Schedule configuration. For ONE_TIME, include runAt. For RECURRING, include cron and endAt, "
			"and optionally startAt and timezone. Use ISO-8601 timestamps where applicable."
		),
	)
	operations: list[CreateOperationModel] = Field(
		description="Ordered operations that define the full execution plan.",
		min_length=1,
	)


@mcp.tool(
	name="createOrder",
	description="Create a new order with its schedule, operations, and action plan.",
)
def create_order(
	userId: Annotated[
		str,
		Field(description="User ID for whom the order should be created.", min_length=1),
	],
	schedule: Annotated[
		CreateScheduleModel,
		Field(description="Schedule definition and execution plan for the order."),
	],
	conversationId: Annotated[
		Optional[str],
		Field(description="Optional conversation ID related to this order request."),
	] = None,
	title: Annotated[
		Optional[str],
		Field(description="Optional title for the order."),
	] = None,
	description: Annotated[
		Optional[str],
		Field(description="Optional description explaining the order intent."),
	] = None,
) -> dict:
	"""Create an order from the provided plan and return the result."""
	payload = {
		"userId": userId,
		"conversationId": conversationId,
		"schedule": schedule.model_dump(exclude_none=True),
		"title": title,
		"description": description,
	}
	payload = {key: value for key, value in payload.items() if value is not None}

	try:
		return call_sup_fun("create-order-tool-function", payload)
	except Exception as exc:
		return {
			"success": False,
			"function": "create-order-tool-function",
			"error": str(exc),
		}

